In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
current_path = os.getcwd()

In [3]:
current_path

'/Users/alphilritch/covid-19-data/live'

In [4]:
data = pd.read_csv("us-states.csv")

In [7]:
data[data['state'] == 'Alabama']

,date,state,fips,cases,deaths,confirmed_cases,confirmed_deaths,probable_cases,probable_deaths
0,2021-05-03,Alabama,1,528597,10913,408901.0,8602.0,119696.0,2311.0

In [9]:
data = pd.read_csv('/Users/alphilritch/covid-19-data/live/us-states.csv')

In [10]:
data

,date,state,fips,cases,deaths,confirmed_cases,confirmed_deaths,probable_cases,probable_deaths
0,2021-05-03,Alabama,1,528597,10913,408901.0,8602.0,119696.0,2311.0
1,2021-05-03,Alaska,2,67598,330,0.0,330.0,67598.0,0.0
2,2021-05-03,Arizona,4,863927,17344,NaN,NaN,NaN,NaN
3,2021-05-03,Arkansas,5,335968,5741,263096.0,4561.0,72872.0,1180.0
4,2021-05-03,California,6,3745021,61895,3720367.0,61477.0,24654.0,418.0
5,2021-05-03,Colorado,8,516337,6438,NaN,NaN,NaN,NaN
6,2021-05-03,Connecticut,9,339233,8097,NaN,NaN,NaN,NaN
7,2021-05-03,Delaware,10,104909,1626,NaN,NaN,NaN,NaN
8,2021-05-03,District of Columbia,11,47855,1106,47855.0,1106.0,0.0,0.0
9,2021-05-03,Florida,12,2242770,35267,0.0,35267.0,2242770.0,0.0
10,2021-05-03,Georgia,13,1078321,19586,857790.0,17105.0,220531.0,2481.0
11,2021-05-03,Guam,66,8944,137,8726.0,137.0,218.0,0.0
12,2021-05-03,Hawaii,15,32989,480,NaN,NaN,NaN,NaN
13,2021-05-03,Idaho,16,187728,2048,150423.0,1784.0,37305.0,264.0
14,2021-05-03,Illinois,17,1343273,24358,1213803.0,22073.0,129470.0,2285.0
15,2021-05-03,Indiana,18,725964,13349,722646.0,12937.0,3318.0,412.0
16,2021-05-03,Iowa,19,365519,5959,301749.0,NaN,63770.0,NaN
17,2021-05-03,Kansas,20,311218,5025,NaN,NaN,NaN,NaN
18,2021-05-03,Kentucky,21,448339,6634,NaN,NaN,NaN,NaN
19,2021-05-03,Louisiana,22,458581,10382,389487.0,9464.0,69094.0,918.0
20,2021-05-03,Maine,23,61847,789,46023.0,789.0,15824.0,0.0
21,2021-05-03,Maryland,24,449180,8776,448989.0,8585.0,191.0,191.0
22,2021-05-03,Massachusetts,25,691172,17621,647768.0,17270.0,43404.0,351.0
23,2021-05-03,Michigan,26,939387,18883,845064.0,17766.0,94323.0,1117.0
24,2021-05-03,Minnesota,27,579328,7253,539898.0,6766.0,39430.0,487.0
25,2021-05-03,Mississippi,28,311900,7199,190713.0,4969.0,121187.0,2230.0
26,2021-05-03,Missouri,29,602390,9253,533531.0,4414.0,68859.0,4839.0
27,2021-05-03,Montana,30,109106,1574,109106.0,1574.0,0.0,0.0
28,2021-05-03,Nebraska,31,220127,2366,44546.0,457.0,175581.0,1909.0
29,2021-05-03,Nevada,32,315438,5464,315438.0,5464.0,0.0,0.0
30,2021-05-03,New Hampshire,33,95377,1305,0.0,NaN,95377.0,NaN
31,2021-05-03,New Jersey,34,1000009,25600,875277.0,22975.0,124732.0,2625.0
32,2021-05-03,New Mexico,35,197733,4069,197733.0,4069.0,0.0,0.0
33,2021-05-03,New York,36,2053027,51830,2039325.0,46734.0,13702.0,5096.0
34,2021-05-03,North Carolina,37,976985,12677,838637.0,11205.0,138348.0,1472.0
35,2021-05-03,North Dakota,38,107739,1525,99512.0,NaN,8227.0,NaN
36,2021-05-03,Northern Mariana Islands,69,168,2,168.0,2.0,0.0,0.0
37,2021-05-03,Ohio,39,1075004,19284,NaN,NaN,NaN,NaN
38,2021-05-03,Oklahoma,40,448305,6788,0.0,6788.0,448305.0,0.0
39,2021-05-03,Oregon,41,186344,2516,0.0,NaN,186344.0,NaN
40,2021-05-03,Pennsylvania,42,1161184,26327,NaN,NaN,NaN,NaN
41,2021-05-03,Puerto Rico,72,166193,2313,116781.0,0.0,49412.0,2313.0
42,2021-05-03,Rhode Island,44,148186,2671,0.0,NaN,148186.0,NaN
43,2021-05-03,South Carolina,45,580273,9520,482907.0,8379.0,97366.0,1141.0
44,2021-05-03,South Dakota,46,122660,1967,107689.0,NaN,14971.0,NaN
45,2021-05-03,Tennessee,47,832935,12100,685569.0,1950.0,147366.0,10150.0
46,2021-05-03,Texas,48,2897234,50473,2504951.0,24310.0,392283.0,26163.0
47,2021-05-03,Utah,49,398077,2204,0.0,2139.0,398077.0,65.0
48,2021-05-03,Vermont,50,23126,247,0.0,NaN,23126.0,NaN
49,2021-05-03,Virginia,51,661314,10791,NaN,NaN,NaN,NaN
50,2021-05-03,Virgin Islands,78,3138,27,3138.0,27.0,0.0,0.0
51,2021-05-03,Washington,53,406659,5547,373604.0,311.0,33055.0,5236.0
52,2021-05-03,West Virginia,54,153918,2686,121016.0,2249.0,32902.0,437.0
53,2021-05-03,Wisconsin,55,661890,7567,599227.0,6839.0,62663.0,728.0
54,2021-05-03,Wyoming,56,58142,707,49101.0,NaN,9041.0,NaN